definitions:
  err.Err:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  err.Message:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/projects/:
    post:
      description: |-
        make all request to github to update repositories, milestones
        If don't get from gh some repos delete it in db
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/err.Err'
      summary: Update all projects
swagger: "2.0"
