definitions:
  err.Err:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  err.Message:
    properties:
      message:
        type: string
    type: object
  functask.FuncTask:
    properties:
      func_task_url:
        type: string
      milestone_id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/projects/:
    post:
      description: |-
        make all request to github to update repositories, milestones
        If don't get from gh some repos delete it in db
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/err.Err'
      summary: Update all projects
  /api/v1/projects/add/functask:
    post:
      consumes:
      - application/json
      description: |-
        add func task to milestone
        if func task is exist for milesotne will replace it
      parameters:
      - description: function task that you want to add
        in: body
        name: functask
        required: true
        schema:
          $ref: '#/definitions/functask.FuncTask'
      responses:
        "201":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
      summary: add func task to milestone
swagger: "2.0"
