trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: BuildAndPush
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/itlab-projects-back'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/api/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/src/api/'
        tags: |
          $(tag)
          latest
