version: "3.8"
services:
  projects-back:
    build:
      context: "${BACK_PROJECTS_CONTEXT-.}/src/ITLab-Projects"
    ports:
      - 5505:5505
    environment:
      ITLAB_PROJECTS_DBURI: mongodb://root:root@db:27017/itlab-projects
      ITLAB_PROJECTS_DBURI_TEST: mongodb://root:root@db:27017/itlab-projects-test
      ITLAB_PROJECTS_ACCESSKEY: some_access_key
      ITLABPROJ_ROLES: "projects projects.admin"
      ITLABPROJ_KEYURL: https://example.com
      ITLABPROJ_AUDIENCE: audiance
      ITLABPROJ_ISSUER: https://example.com
      ITLAB_PROJECTS_APPPORT: 5505
      ITLAB_PROJECTS_TESTMODE: "true"
      ITLAB_PROJECTS_UPDATETIME: 2h
  db:
    image: "mongo:latest"
    ports:
      - 27018:27017
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: itlab-projects
