basePath: /api/projects
definitions:
  assignee.Assignee:
    properties:
      avatar_url:
        type: string
      html_url:
        type: string
      id:
        type: integer
      login:
        type: string
    type: object
  err.Err:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  err.Message:
    properties:
      message:
        type: string
    type: object
  estimate.AddEstimateReq:
    properties:
      file_id:
        type: string
    type: object
  estimate.Estimate:
    properties:
      estimate_url:
        type: string
      milestone_id:
        type: integer
    type: object
  functask.AddFuncTaskReq:
    properties:
      file_id:
        type: string
    type: object
  functask.FuncTask:
    properties:
      func_task_url:
        type: string
      milestone_id:
        type: integer
    type: object
  label.Label:
    properties:
      color:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      node_id:
        type: string
      type:
        type: string
      url:
        type: string
    type: object
  landing.Landing:
    properties:
      date:
        type: string
      description:
        type: string
      developers:
        items:
          type: string
        type: array
      id:
        type: integer
      images:
        items:
          type: string
        type: array
      site:
        type: string
      sourceCode:
        items:
          $ref: '#/definitions/landing.SourceCode'
        type: array
      tags:
        items:
          type: string
        type: array
      tech:
        items:
          type: string
        type: array
      title:
        type: string
      videos:
        items:
          type: string
        type: array
    type: object
  landing.LandingCompact:
    properties:
      date:
        type: string
      id:
        type: integer
      images:
        items:
          type: string
        type: array
      tags:
        items:
          type: string
        type: array
      title:
        type: string
    type: object
  landing.SourceCode:
    properties:
      link:
        description: repository link
        type: string
      name:
        type: string
    type: object
  milestone.Issue:
    properties:
      assignees:
        items:
          $ref: '#/definitions/assignee.Assignee'
        type: array
      body:
        type: string
      closed_at:
        type: string
      created_at:
        type: string
      html_url:
        type: string
      id:
        type: integer
      labels:
        items:
          $ref: '#/definitions/label.Label'
        type: array
      number:
        type: integer
      project_path:
        type: string
      pull_request:
        $ref: '#/definitions/pullrequest.PullRequest'
      reppath:
        type: string
      state:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/user.User'
    type: object
  milestone.IssuesWithMilestoneID:
    properties:
      assignees:
        items:
          $ref: '#/definitions/assignee.Assignee'
        type: array
      body:
        type: string
      closed_at:
        type: string
      created_at:
        type: string
      deleted:
        type: boolean
      html_url:
        type: string
      id:
        type: integer
      labels:
        items:
          $ref: '#/definitions/label.Label'
        type: array
      milestone_id:
        type: integer
      number:
        type: integer
      project_path:
        type: string
      pull_request:
        $ref: '#/definitions/pullrequest.PullRequest'
      repo_id:
        type: integer
      reppath:
        type: string
      state:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/user.User'
    type: object
  milestone.Milestone:
    properties:
      closed_issues:
        type: integer
      creator:
        $ref: '#/definitions/user.User'
      deleted:
        type: boolean
      description:
        type: string
      estimate:
        $ref: '#/definitions/estimate.Estimate'
      func_task:
        $ref: '#/definitions/functask.FuncTask'
      id:
        type: integer
      issues:
        items:
          $ref: '#/definitions/milestone.Issue'
        type: array
      number:
        type: integer
      open_issues:
        type: integer
      state:
        type: string
      title:
        type: string
    type: object
  pullrequest.PullRequest:
    properties:
      diff_url:
        type: string
      html_url:
        type: string
      patch_url:
        type: string
      url:
        type: string
    type: object
  realese.Realese:
    properties:
      html_url:
        type: string
      id:
        type: integer
      url:
        type: string
    type: object
  repo.Repo:
    properties:
      archived:
        type: boolean
      contributors:
        items:
          $ref: '#/definitions/user.User'
        type: array
      created_at:
        type: string
      deleted:
        type: boolean
      description:
        type: string
      html_url:
        description: "Path\t\t\t\tstring\t\t\t`json:\"path_with_namespace,omitempty\"`"
        type: string
      id:
        type: integer
      language:
        type: string
      languages:
        additionalProperties:
          type: integer
        type: object
      name:
        type: string
      pushed_at:
        type: string
      updated_at:
        type: string
    type: object
  repoasproj.RepoAsProj:
    properties:
      completed:
        type: number
      last_realese:
        $ref: '#/definitions/realese.Realese'
      milestones:
        items:
          $ref: '#/definitions/milestone.Milestone'
        type: array
      repo:
        $ref: '#/definitions/repo.Repo'
      tags:
        items:
          $ref: '#/definitions/tag.Tag'
        type: array
    type: object
  repoasproj.RepoAsProjCompact:
    properties:
      completed:
        type: number
      repo:
        $ref: '#/definitions/repo.Repo'
      tags:
        items:
          $ref: '#/definitions/tag.Tag'
        type: array
    type: object
  tag.Tag:
    properties:
      tag:
        type: string
    type: object
  user.User:
    properties:
      avatar_url:
        type: string
      html_url:
        type: string
      id:
        type: integer
      login:
        type: string
    type: object
info:
  contact: {}
  description: This is a server to get projects from github
  title: ITLab-Projects API
  version: "1.0"
paths:
  /v1/estimate/{milestone_id}:
    delete:
      description: delete estimate from database
      parameters:
      - description: should be uint
        in: path
        name: milestone_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "403":
          description: if you are not admin
          schema:
            $ref: '#/definitions/err.Message'
        "404":
          description: estimate not found
          schema:
            $ref: '#/definitions/err.Message'
        "409":
          description: some problems with microfileservice
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Failed to delete estimate
          schema:
            $ref: '#/definitions/err.Message'
      summary: delete estimate from database
      tags:
      - estimate
    post:
      consumes:
      - application/json
      description: |-
        add estimate to milestone
        if estimate is exist for milesotne will replace it
      parameters:
      - description: estimate that you want to add
        in: body
        name: estimate
        required: true
        schema:
          $ref: '#/definitions/estimate.AddEstimateReq'
      - description: id of milestone
        in: path
        name: milestone_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: Unexpected body
          schema:
            $ref: '#/definitions/err.Message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "403":
          description: if you are not admin
          schema:
            $ref: '#/definitions/err.Message'
        "404":
          description: Don't find milestone with this id
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Failed to save estimate
          schema:
            $ref: '#/definitions/err.Message'
      summary: add estimate to milestone
      tags:
      - estimate
  /v1/issues:
    get:
      description: return issues according to query params
      parameters:
      - description: represent how mush skip first issues
        in: query
        name: start
        type: integer
      - description: set limit of getting issues standart and max 50
        in: query
        name: count
        type: integer
      - description: search to name of issues, title of milestones and repository
          names
        in: query
        name: name
        type: string
      - description: search of label name of issues
        in: query
        name: tag
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/milestone.IssuesWithMilestoneID'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
      summary: return issues
      tags:
      - issues
  /v1/issues/labels:
    get:
      description: return all unique labels of issues
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
      summary: return labels
      tags:
      - issues
  /v1/projects:
    get:
      description: |-
        return a projects you can filter count of them
        tags, name
      parameters:
      - description: represents the number of skiped projects
        in: query
        name: start
        type: integer
      - description: represent a limit of projects, standart and max count equal 50
        in: query
        name: count
        type: integer
      - description: use to filter projects by tag
        in: query
        name: tag
        type: string
      - description: use to filter by name
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/repoasproj.RepoAsProjCompact'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Failed to get repositories
          schema:
            $ref: '#/definitions/err.Message'
      summary: return projects according to query value
      tags:
      - projects
    post:
      description: make all request to github to update repositories, milestones
      responses:
        "200":
          description: ""
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "403":
          description: if you are nor admin
          schema:
            $ref: '#/definitions/err.Message'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/err.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
      summary: Update all projects
      tags:
      - projects
  /v1/projects/{id}:
    delete:
      description: delete project by id and all milestones in it
      parameters:
      - description: id of project
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ""
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "403":
          description: if you are not admin
          schema:
            $ref: '#/definitions/err.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/err.Message'
        "409":
          description: some problems with microfileservice
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
      summary: delete project by id
      tags:
      - projects
    get:
      description: return a project according to id value in path
      parameters:
      - description: a uint value of repository id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/repoasproj.RepoAsProj'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
      summary: return project according to id
      tags:
      - projects
  /v1/projects/landing:
    get:
      parameters:
      - description: represent how much landins need to skip
        in: query
        name: start
        type: integer
      - description: represent a max count of returing landing
        in: query
        name: count
        type: integer
      - description: return a landings with this tags
        in: query
        name: tag
        type: string
      - description: return landing with this names
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/landing.LandingCompact'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
      summary: return all landings according to path params
      tags:
      - projects
  /v1/projects/landing/{id}:
    get:
      description: return a landing according to id
      parameters:
      - description: id of landing
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/landing.Landing'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
      summary: return a current landing
      tags:
      - projects
  /v1/tags:
    get:
      description: return all tags
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/tag.Tag'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Message'
      summary: return all tags
      tags:
      - tags
  /v1/task/{milestone_id}:
    delete:
      description: delete functask from database
      parameters:
      - description: should be uint
        in: path
        name: milestone_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "403":
          description: if you are not admin
          schema:
            $ref: '#/definitions/err.Message'
        "404":
          description: func task not found
          schema:
            $ref: '#/definitions/err.Message'
        "409":
          description: some problems with microfileservice
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Failed to delete func task
          schema:
            $ref: '#/definitions/err.Message'
      summary: delete functask from database
      tags:
      - functask
    post:
      consumes:
      - application/json
      description: |-
        add func task to milestone
        if func task is exist for milesotne will replace it
      parameters:
      - description: function task that you want to add
        in: body
        name: functask
        required: true
        schema:
          $ref: '#/definitions/functask.AddFuncTaskReq'
      - description: id of milestone
        in: path
        name: milestone_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: Unexpected body
          schema:
            $ref: '#/definitions/err.Message'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/err.Message'
        "403":
          description: if you are not admin
          schema:
            $ref: '#/definitions/err.Message'
        "404":
          description: Don't find milestone with this id
          schema:
            $ref: '#/definitions/err.Message'
        "500":
          description: Failed to save functask
          schema:
            $ref: '#/definitions/err.Message'
      summary: add func task to milestone
      tags:
      - functask
swagger: "2.0"
