version: "3.7"
services:
    db:
        image: 'mongo:latest'
        ports:
            - '27100:27017'
        volumes:
            - ./mongodb_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
            MONGO_INITDB_DATABASE:      "${MONGO_INITDB_DATABASE}"
        networks: 
            - database
    api:
        build: "./ITLab-Projects"
        container_name: "api"
        volumes: 
            - ./.env:/root/.env
        ports: 
            - 8080:8080
        networks: 
            - database


networks: 
    database:
        driver: "bridge"